const AppStrings = {
  AppName: 'The Longevity Club',
  No: 'No',
  Yes: 'Yes',
  Ok: 'Ok',
  date_format: 'DD-MMM-YYYY',
  date_format_new: 'DD, MMM YYYY',
  date_format_update: 'DD MMM YYYY',
  date_format_for_sql: 'YYYY-MM-DD',
  date_format_for_sql_with_time: 'YYYY-MM-DD hh:mm:ss',
  currency_symbol: '₹',
  currency_name: 'INR',

  // Paytm MerchantKey
  // For live
  mid: 'dYZySO55259113136198',
  callbackUrl: 'https://securegw.paytm.in/theia/paytmCallback?ORDER_ID=',
  // Paytm MerchantKey
  // For test
  //    mid : 'NZpAZu75566887991707',
  //    callbackUrl: 'http://securegw-stage.paytm.in/theia/paytmCallback?ORDER_ID=',

  //error message
  err_check_internet_connection: 'Check your internet connection',
  msg_do_you_want_to_logout: 'Do you want to logout?',

  //media picker dialog
  title_take_photo: 'Take Photo',
  title_choose_from_gallery: 'Choose From Gallery',
  btn_title_cancel: 'Cancel',

  welcome: 'Welcome To TLC!',
  email: 'Email',
  password: 'Password',
  name: 'Name',
  mobile: 'Mobile No',
  createAccount: 'Create your FREE account',
  register: 'Register',
  first_name: 'First Name',
  last_name: 'Last Name',
  confirm_pas: 'Confirm Password',
  mobile: 'Mobile No.',
  submit: 'Submit',
  btn_login_title: 'login',
  btn_homePage_title: 'Home',
  btn_register_title: 'Sign up',
  or_signup_with: 'Or sign up with',
  forgot_password: "Forgot Password?",

  congratulations: 'Congratulations',
  msg_signup_success: 'Your account has been created successfully',
  btn_title_continue: 'Continue',
  txt_please_login: 'Please login into your account',
  txt_email: 'Email',
  txt_password: 'Password',
  txt_or_sign_in_with: 'Or sign in with',
  txt_dont_have_an_account: "not a part of tlc yet?",
  btn_sign_up: 'new sign up here',
  btn_sign_in_as_franchisee_manager: 'login as DSA',
  name: 'Name',
  login: 'Login',
  enterName: 'Please enter your name.',
  enterEmail: 'Please enter your email address.',
  enterPassword: 'Please enter your password.',
  enterMobile: 'Please enter valid phone number.',
  ref_code: 'DSA Code/Mobile',
  msg_enter_valid_email: 'Please enter valid email id',
  subscriptionListText1: 'Book Your',
  subscriptionListText2: 'Subscription Now',
  subscriptionListText3: 'The Longevity Club',
  subscriptionListText4: 'Subscription Options',
  subscriptionListText5: 'Offer Price',
  subscriptionDetailsText1: 'Subscription Details:',
  subscriptionDetailsText2: 'Activation: ',
  subscriptionDetailsText3: 'Validity:',
  subscriptionDetailsText4: 'Benefits:',
  subscriptionDetailsText5: 'Subscribe',
  book: 'book',
  appointment: 'appointment',

  phone: 'phone',
  verify: 'Verify',
  btn_retray: 'Retry',
  HOME: 'Home',
  Logout: 'Logout',
  Profile: 'Profile',
  AddFamilyMembers: 'Add Members',
  FamilyMembersData: 'Family Members',
  success: 'success',
  //Mamography
  allCities: 'all cities',
  alertSelectCenter: 'Please select centre',
  alertSelectTimeSlot: 'Please select time slot',
  alertSelectDate: 'Please select date',
  congratulations: 'Congratulations',
  msg_signup_success: 'Your account has been created successfully',
  btn_title_continue: 'Continue',
  txt_please_login: 'Please login into your account',
  txt_email: 'Email',
  txt_password: 'Password',
  txt_or_sign_in_with: 'Or sign in with',

  name: 'Name',
  login: 'Login',
  enterName: 'Please enter your name.',
  enterEmail: 'Please enter your email address.',
  enterPassword: 'Please enter your password.',
  enterMobile: 'Please enter valid mobile number.',
  ref_code: 'DSA Code/Referral Code',
  msg_enter_valid_email: 'Please enter valid email id',
  subscriptionListText1: 'buy your',
  subscriptionListText2: 'subscription',
  subscriptionListText3: 'the longevity club',
  subscriptionListText4: 'subscription options',
  subscriptionListText5: 'Offer Price',
  subscriptionDetailsText1: 'Subscription Details:',
  subscriptionDetailsText2: 'Activation: ',
  subscriptionDetailsText3: 'Validity:',
  subscriptionDetailsText4: 'benefits:',
  subscriptionDetailsText5: 'Subscribe',
  book: 'book',
  appointment: 'appointment',
  my: 'my',
  profile: 'Profile',
  membershipDetails: 'membership details',
  personalDetails: 'personal details',
  tlcPrime: 'TLC Prime',

  verify: 'Verify',
  btn_retray: 'Retry',
  HOME: 'Home',
  Logout: 'Logout',
  Profile: 'Profile',
  AddFamilyMembers: 'Add Members',
  success: 'success',
  version: 'Version',

  //Mamography
  allCities: 'all cities',
  alertSelectCenter: 'Please select centre',
  settings: 'Settings',
  relation: 'relation',
  AI_Thermo1: 'AI-Based Thermo',
  AI_Thermo2: 'Mammography',
  AI_Thermo3: 'Book Appointment',
  AI_Thermo4: 'Book your appointment with our best service provider.',
  AI_Thermo6: 'Report',
  AI_Thermo7: 'Pending/Download',
  AI_Thermo8: 'Book your appointment with our best\nservice provider.',
  reschedule: 'Reschedule',
  rescheduleMsg:
    'You can Reschedule for free max 2 times. After that rescheduling charges of Rs. 100 will be applied.',
  faqs: 'FAQs',
  city: 'city',
  state: 'state',
  loginAmbassador: 'please login as',
  AmbassadorTitle: 'DSA',
  SponsorDetail: "sponsor's details",
  SponsorSubTitle: "please enter sponsor's mobile",
  order_history: 'Order History',

  //Agent
  welcome_ambassador: 'welcome DSA!',
  text_Want_Pink_Ambassador: 'Want to be a TLC DSA?',
  text_Already_registered_Ambassador: 'Already registered DSA?',
  proceed_to_checkout: 'proceed to checkout',
  text_update_app: 'To use this app, download latest version',
  btn_login_as_user_title: 'continue as club member',
  btn_login_as_agent_title: 'continue as tlc DSA',
  alert_product_sold_out:
    ' this product is sold out , please add other product to cart',
  wellness_revolution: 'you are becoming part of a wellness revolution!',
  sign_up_as_an_ambassador: 'sign up as an\n DSA',
  want_to_be_tlc_ambassador: 'want to be a tlc DSA?',
  already_an_ambassador: 'already an DSA?',

  //Doctor
  view_profile: 'view profile',

  //Payment Drawer
  payment: 'Pay',
  privacy_policy: 'Privacy Policy',
  terms: 'Terms & Condition',

  // subscription detail page
  Limited_period_offer: 'Limited period offer',
  for_signup: 'For Signup : click here',
};

export default AppStrings;
